server:
  port: 8990
eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
    preferIpAddress: ${EUREKA_PREFER_IP:false}
    securePortEnabled: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8990/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    renewalPercentThreshold: ${EUREKA_RENEW_THRESHOLD:0.49}
    renewalThresholdUpdateIntervalMs: ${EUREKA_RENEW_THRESHOLD_PERIOD:30000} 
    
spring:
  application:
    name: aiofg-discovery  